"""Types for the EbookLib APIs used by this project."""

from collections.abc import Iterator, Mapping
from typing import Any

class EpubItem:
    media_type: str

    def get_name(self) -> str: ...
    def get_content(self) -> bytes: ...
    def get_type(self) -> int: ...

class EpubBook:
    spine: list[tuple[str, str] | str]

    def get_metadata(
        self, _namespace: str, _name: str
    ) -> list[tuple[str, Mapping[str, str]] | str | None]: ...
    def get_items(self) -> Iterator[EpubItem]: ...
    def get_item_with_id(self, _item_id: str) -> EpubItem | None: ...

def read_epub(_name: str, _options: Mapping[str, Any] | None = None) -> EpubBook: ...
