"""Shared constants for the EPUB-to-HTML CLI."""

from __future__ import annotations

ALL_OPTIONS = (
    "--help",
    "--version",
    "--print-completion",
    "--output",
    "--workers",
    "--inspect",
    "--strategy",
    "--wrap",
    "--css",
    "--remove-toc",
    "--remove-cover",
    "--images-dir-name",
    "--chunked",
    "--safe-mode",
    "--navigation",
    "--reader-max-width",
    "--reader-font-family",
    "--force",
    "--deadline-seconds",
    "--fail-on-warning",
    "--no-validate-output",
    "--stable-mime-types",
    "--newline",
    "--report-json",
    "--report-html",
    "--spine-range",
    "--exclude-content",
    "--preserve-internal-css",
    "--svg-policy",
    "--mathml-policy",
    "--media-policy",
    "--font-policy",
    "--no-progress",
    "--force-progress",
    "--verbose",
    "--max-archive-entries",
    "--max-compressed-bytes",
    "--max-expanded-bytes",
    "--max-entry-bytes",
    "--max-compression-ratio",
    "--max-documents",
    "--max-images",
    "--max-output-bytes",
)
SHORT_OPTIONS = ("-h", "-o", "-s", "-w", "-c")
_COMPLETION_WORDS = " ".join((*ALL_OPTIONS, *SHORT_OPTIONS))
